
input_queries: "/home/vishal-naik/naikvish-ws/ORE_runs/query_examples/vectara_research.csv"  # file with a list of queries to use for evaluation

# Evaluation results are written to the "results_folder" folder.
# You can override the names of files in this folder by specifying 'generated_answers', 'eval_results_file', and 'metrics_file'.
results_folder: "/home/vishal-naik/naikvish-ws/ORE_runs/ORE_resultsllama_parallel"
generated_answers: "vectara_research_answers.csv"
eval_results_file: "vectara_research_results.csv"
metrics_file: "vectara_research_metrics.png"

evaluator:
  type: "TRECEvaluator"  
  model:
    type: "OpenAIModel"
    name: "gpt-4o-mini"
    api_key: ${oc.env:OPENAI_API_KEY}  # Reads from environment variable.
  options:
    # The k values to evaluate metrics like precision@k at.
    k_values: [1, 3, 5, 10]    

connector:
  type: "LlamaIndexConnector"  
  options:
    # the folder with the files to be indexed into LlamaIndex
    # all files in this folder and any subfolders will be indexed
    folder: "/home/vishal-naik/naikvish-ws/ORE_runs/vectara_docs"
    top_k: 10
    max_workers: -1  # -1 to use all available CPU cores for parallel processing.
